export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  CLIENT = 'CLIENT'
}

export enum Permission {
  VIEW_ARTICLES = 'VIEW_ARTICLES',
  CREATE_ARTICLES = 'CREATE_ARTICLES',
  EDIT_ARTICLES = 'EDIT_ARTICLES',
  DELETE_ARTICLES = 'DELETE_ARTICLES',
  VIEW_STOCK = 'VIEW_STOCK',
  MANAGE_STOCK = 'MANAGE_STOCK',
  VIEW_INVOICES = 'VIEW_INVOICES',
  CREATE_INVOICES = 'CREATE_INVOICES',
  VIEW_CLIENTS = 'VIEW_CLIENTS',
  MANAGE_CLIENTS = 'MANAGE_CLIENTS',
  VIEW_SUPPLIERS = 'VIEW_SUPPLIERS',
  MANAGE_SUPPLIERS = 'MANAGE_SUPPLIERS',
  VIEW_ACCOUNTING = 'VIEW_ACCOUNTING',
  MANAGE_ACCOUNTING = 'MANAGE_ACCOUNTING',
  VIEW_PAYROLL = 'VIEW_PAYROLL',
  MANAGE_PAYROLL = 'MANAGE_PAYROLL',
  VIEW_PRESENCE = 'VIEW_PRESENCE',
  MANAGE_PRESENCE = 'MANAGE_PRESENCE',
  VIEW_USERS = 'VIEW_USERS',
  MANAGE_USERS = 'MANAGE_USERS',
  VIEW_REPORTS = 'VIEW_REPORTS',
  MANAGE_SETTINGS = 'MANAGE_SETTINGS'
}

export enum SubscriptionPlan {
  FREE = 'FREE',
  STARTER = 'STARTER',
  PROFESSIONAL = 'PROFESSIONAL',
  ENTERPRISE = 'ENTERPRISE'
}
